# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5fbe5ba180b2169eeb9fd39f1e14970cd57ce2304724e3a6a7420048c2c276f06581e3efe5e6c6cafc41e357a3a37c1229cdb57dbc0557eff8a72bf80855470

test:
  secret_key_base: ea68a458251729d2321bec3f900fe4dbd3e56fe4a6660dac5e7c88f7a71e09c7ebfce748c049fb847be5f776425a0fbf920e5dab1a4910a2d1889a015d1c441d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
